// Data Fakultas dan Program Studi
export const facultiesData = {
  'Agama Islam': [
    'Tafsir Hadist',
    'Hukum Keluarga (Ahwal Al-Syakhshiyyah)',
    'Hukum Ekonomi Syari\'ah (Muamalah)',
    'Pendidikan Agama Islam',
    'Pendidikan Bahasa Arab',
    'Pendidikan Guru Madrasah Ibtidaiyah (PGMI)',
    'Komunikasi dan Penyiaran Islam',
  ],
  'Ekonomi': [
    'Ilmu Ekonomi dan Studi Pembangunan',
    'Manajemen',
    'Akuntansi',
  ],
  'Teknik': [
    'Teknik Sipil',
    'Teknik Mesin',
    'Teknik Elektro',
    'Arsitektur',
  ],
  'Hukum': [
    'Ilmu Hukum',
  ],
  'Sastra': [
    'Sastra Inggris',
    'Sastra Indonesia',
    'Bahasa dan Sastra Arab',
    'Ilmu Komunikasi',
    'Pendidikan Bahasa Inggris',
    'Pendidikan Bahasa dan Sastra Indonesia',
  ],
  'Perikanan dan Ilmu Kelautan': [
    'Budidaya Perairan',
    'Pemanfaatan Sumber Daya Perikanan',
    'Ilmu Kelautan',
  ],
  'Pertanian': [
    'Agroteknologi',
    'Agribisnis',
  ],
  'Teknologi Industri': [
    'Teknik Industri',
    'Teknik Kimia',
    'Teknik Pertambangan',
  ],
  'Kedokteran': [
    'Kedokteran Umum',
  ],
  'Ilmu Komputer': [
    'Teknik Informatika',
    'Sistem Informasi',
  ],
  'Kesehatan Masyarakat': [
    'Kesehatan Masyarakat',
    'Ilmu Keperawatan',
    'Kebidanan',
  ],
  'Farmasi': [
    'Farmasi',
  ],
  'Kedokteran Gigi': [
    'Kedokteran Gigi',
  ],
};

export const faculties = Object.keys(facultiesData);

export const indonesianCities = [
  'Ambon',
  'Balikpapan',
  'Banda Aceh',
  'Bandar Lampung',
  'Bandung',
  'Banjarbaru',
  'Banjarmasin',
  'Batam',
  'Batu',
  'Bau-Bau',
  'Bekasi',
  'Bengkulu',
  'Bima',
  'Binjai',
  'Bitung',
  'Blitar',
  'Bogor',
  'Bontang',
  'Bukittinggi',
  'Cilegon',
  'Cimahi',
  'Cirebon',
  'Denpasar',
  'Depok',
  'Dumai',
  'Gorontalo',
  'Gunungsitoli',
  'Jakarta Barat',
  'Jakarta Pusat',
  'Jakarta Selatan',
  'Jakarta Timur',
  'Jakarta Utara',
  'Jambi',
  'Jayapura',
  'Kediri',
  'Kendari',
  'Kota Administrasi Jakarta Barat',
  'Kota Administrasi Jakarta Pusat',
  'Kota Administrasi Jakarta Selatan',
  'Kota Administrasi Jakarta Timur',
  'Kota Administrasi Jakarta Utara',
  'Kotamobagu',
  'Kupang',
  'Langsa',
  'Lhokseumawe',
  'Lubuklinggau',
  'Madiun',
  'Magelang',
  'Makassar',
  'Malang',
  'Manado',
  'Mataram',
  'Medan',
  'Metro',
  'Mojokerto',
  'Padang',
  'Padang Panjang',
  'Padang Sidempuan',
  'Pagar Alam',
  'Palangkaraya',
  'Palembang',
  'Palopo',
  'Palu',
  'Pangkal Pinang',
  'Parepare',
  'Pariaman',
  'Pasuruan',
  'Payakumbuh',
  'Pekalongan',
  'Pekanbaru',
  'Pematang Siantar',
  'Pontianak',
  'Prabumulih',
  'Probolinggo',
  'Purwokerto',   // meski bukan kota administratif, sering digunakan/dianggap kota
  'Salatiga',
  'Samarinda',
  'Sawahlunto',
  'Semarang',
  'Serang',
  'Sibolga',
  'Singkawang',
  'Sleman',       // umum, meskipun kabupaten, tapi pusatnya banyak dikenal sebagai "kota"
  'Solok',
  'Sorong',
  'Subulussalam',
  'Sukabumi',
  'Sungai Penuh',
  'Surabaya',
  'Surakarta',
  'Tangerang',
  'Tangerang Selatan',
  'Tanjung Balai',
  'Tanjung Pinang',
  'Tarakan',
  'Tasikmalaya',
  'Tebing Tinggi',
  'Tegal',
  'Ternate',
  'Tidore Kepulauan',
  'Tomohon',
  'Tual',
  'Yogyakarta',
  'Lainnya',
];

export const genders = [
  'Laki-laki',
  'Perempuan',
];
